### ISSUE TITLE
Add Description to Labels

### ISSUE THREAD

**Issue by adam0306** [TheMediocreCoder/CyberArk_RDPFile_Connector#1]
It would be helpful to the users to have some more description of each labels, examples to the side of the text boxes, or an example within each textbox when textbox is empty.

- Username - Field must be in domain\user format.

- Target Username - User cannot be in domain\user format.

- Target Address - Address cannot be in FQDN and must be in either hostname or IP format.

**Comment by TheMediocreCoder** [comment]
Resolved.
Hitting enter (Return) key would submit the form


$Generate_PSM_RDP_File.AcceptButton = $bttn_Connect
