### ISSUE TITLE
Add AutoSelection

### ISSUE THREAD

**Issue by adam0306** [TheMediocreCoder/CyberArk_RDPFile_Connector#2]
If possible when all textboxes are filled have the "Connect To Target via CyberArk" button autoselected so that you can press enter instead of having to use a mouse. Maybe shorten the button label to something such as "Connect via CyberArk"

**Comment by TheMediocreCoder** [comment]
Added Balloon Tool Tip on Mouse Hover & Mouse Click events for below Text Fields 

Username  = "Username should be in format Domain\Username. Target Username can only contain AlphaNum _ (underscore) -(hyphen)"

Target Username - "Target Username cannot be in domain\user format. Target Username can only contain AlphaNum _ (underscore) -(hyphen)"

Target Address = "Address must be in either FQDN,hostname or IP format"
