### ISSUE TITLE
Username field does not support dashes

### ISSUE THREAD

**Issue by ixtlanian** [TheMediocreCoder/CyberArk_RDPFile_Connector#3]
When entering a domain or a username with a dash (which is permitted by Microsoft naming standards), the following error is generated:
Username should be in format Domain\Username

Examples of combinations causing error:
dom-ain\user
domain\us-er
dom-ain\us-er

On a separate note, a mouse-on tooltip on Username field should be corrected. "Target username" should be corrected to "Username" in the second sentence. This seems to be a copy/paste error from Target Username field.

**Comment by TheMediocreCoder** [comment]
Hey @ixtlanian ,
Thanks for reporting the issue.
I've fixed it. Can you please have a look now. Both of the issues should be fixed.

Feel free to submit a feature request.
